# Generated by Django 6.0 on 2026-05-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0008_detection_accuracy_detection_ratio_predict_hot_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregister_model',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
